### ISSUE TITLE
Create Basic Backend

### ISSUE THREAD

**Issue by Jacky-Ickx** [cakedgroup/getcaked#19]
Create the most basic Backend and API by doing the following:

- [x] Create database with Tables for Groups and Users
- [x] Create Services interacting with the database
- [x] Create API for Groups and Users
- [x] JWT Tokens

**Comment by grossamos** [comment]
Created a rough ERM for this (mostly to practice for the upcoming exams):
![image](https://user-images.githubusercontent.com/54294591/141257783-fd1aab04-a0b4-498f-b546-1ca1f43c7252.png)
If not already implemented by @Jacky-Ickx, the question that might still have to be answered here is if we should merge the ``is admin of`` relationship into the ``is member in`` as a bool. 
Currently the ERM does not force an admin to be a member of a group (which we explicitly want), however adding it in as a property might make it a little more inefficient to find the admin of a group.

**Comment by grossamos** [comment]
*also for some reason still included ``groupname`` as a property of Cake Event, this is obviously incorrect and will be removed while implementing

**Comment by Jacky-Ickx** [comment]
`is admin of` should not be a bool in `is member in`, but rather an attribute of `Group`.
Other than that, one could argue, whether `got caked` and `was caked in` should be attributes of `Cake Event` since both are at most 1:N relations.
Further, I don't see why a `Cake Event` wouldn't be allowed to be `approved by` more than 3 Users? If that is meant as a threshold, doing this in the Backend would be better, since we wouldn't be limiting ourselves upfront and be able to change said threshold later on/ on a 'per group' basis. Adding to that, such limits are hard to implement in the database itself (in most cases going as far as being upright impossible, which I'd guess is also the case for sqlite)

Marks: 1,8
Verbal assessment: Model would work and is already quite good, but not optimal/prefect

**Comment by grossamos** [comment]
About the two points regarding adding the respective user/group in as a key, I fully agree, just remember foreign keys aren't a thing in ERMs. 
So the relationship definetly still has to exist in the drawing above but will simply be merged during the creation of our RM.

But yeah, about the point of not limiting cake event approvals, your suggestion of having no upper limits would also by fine in my books.

**Comment by Jacky-Ickx** [comment]
Apart from CakeEvents, the /users path should now be finished. :relieved: 

Onto /groups and /cakeevents. :sweat_smile:

**Comment by grossamos** [comment]
good stuff :+1:
