### ISSUE TITLE
Add basic update functionality to admin pannel

### ISSUE THREAD

**Issue by grossamos** [cakedgroup/getcaked#44]
Currently an admin can't update f. ex. the name of a group.

Let's provide all functionality already implemented in the backend from our frontend as well.

**Comment by Jacky-Ickx** [comment]
since there is no functionality regarding changing info yet, this can be considered closed, I guess :P

for real now, I'm just gonna implement said functionality

**Comment by grossamos** [comment]
Possible amendment to story: add patch methods in `groupController`?

**Comment by grossamos** [comment]
Changing a group name is quite easy to implement and would be "nice to have", an idea would maybe be to postpone this and to check if have time to complete this issue at a later date.
